# Generated by Django 4.0.3 on 2022-03-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_default.png', upload_to='profile_image'),
        ),
    ]
